// <auto-generated />
using System;
using AIM.BookStoreManagement.DB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIM.BookStoreManagement.DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251007162400_made_biography_optional")]
    partial class made_biography_optional
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIM.BookStoreManagement.DB.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BioGraphy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3f0f7f0-0220-42b7-a859-00100a7d97b3"),
                            BioGraphy = "The late, great fantasy author.",
                            Name = "Terry Pratchett"
                        },
                        new
                        {
                            Id = new Guid("c3f0f7f0-0220-42b7-a859-00100a7d97b4"),
                            BioGraphy = "Master of social science fiction.",
                            Name = "Ursula K. Le Guin"
                        });
                });

            modelBuilder.Entity("AIM.BookStoreManagement.DB.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Pages")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearPublished")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("801c6b02-efda-48a7-9df7-badf28f091f2"),
                            AuthorId = new Guid("c3f0f7f0-0220-42b7-a859-00100a7d97b3"),
                            Pages = 0,
                            Title = "Guards! Guards!",
                            YearPublished = 1989
                        },
                        new
                        {
                            Id = new Guid("625b97d7-0413-4fb2-9b76-cb5b2531cfc0"),
                            AuthorId = new Guid("c3f0f7f0-0220-42b7-a859-00100a7d97b4"),
                            Pages = 0,
                            Title = "A Wizard of Earthsea",
                            YearPublished = 1968
                        });
                });

            modelBuilder.Entity("AIM.BookStoreManagement.DB.Entities.Book", b =>
                {
                    b.HasOne("AIM.BookStoreManagement.DB.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("AIM.BookStoreManagement.DB.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
